services:
  wxfdashboardsaio_grafana:
    container_name: wxfdashboardsaio_grafana
    environment:
      TZ: 
    image: lux4rd0/weatherflow-dashboards-grafana:latest
    ports:
    - protocol: tcp
      published: 3000
      target: 3000
    restart: always
    volumes:
    - wxfdashboardsaio-grafana-data:/var/lib/grafana
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.flyywx-rtr.entrypoints=https"
      - "traefik.http.routers.flyywx-rtr.rule=Host(`wx.flyy.pt`)"
      - "traefik.http.routers.flyywx-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.flyywx-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.flyywx-rtr.service=flyywx-svc"
      - "traefik.http.services.flyywx-svc.loadbalancer.server.port=80"
  wxfdashboardsaio_influxdb:
    container_name: wxfdashboardsaio_influxdb
    environment:
      TZ: 
      INFLUXDB_ADMIN_PASSWORD: Gk372Qm70E0xGVIcUpSyRiwqfAyhuwkS
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_DATA_ENGINE: tsm1
      INFLUXDB_DB: weatherflow
      INFLUXDB_HTTP_LOG_ENABLED: "false"
      INFLUXDB_LOGGING_FORMAT: json
      INFLUXDB_LOGGING_LEVEL: info
      INFLUXDB_MONITOR_STORE_DATABASE: _internal
      INFLUXDB_MONITOR_STORE_ENABLED: "true"
      INFLUXDB_REPORTING_DISABLED: "true"
      INFLUXDB_USER: weatherflow
      INFLUXDB_USER_PASSWORD: x8egQTrf4bGl8Cs3XGyF1yE0b06pfgJe
    image: influxdb:1.8
    ports:
    - protocol: tcp
      published: 8086
      target: 8086
    restart: always
    volumes:
    - wxfdashboardsaio-influxdb-data:/var/lib/influxdb:rw
  wxfdashboardsaio-collector:
    container_name: wxfdashboardsaio-collector-d041e722
    environment:
      TZ: 
      WEATHERFLOW_COLLECTOR_DEBUG: "false"
      WEATHERFLOW_COLLECTOR_DEBUG_CURL: "false"
      WEATHERFLOW_COLLECTOR_DISABLE_HEALTH_CHECK: "false"
      WEATHERFLOW_COLLECTOR_DISABLE_HOST_PERFORMANCE: "false"
      WEATHERFLOW_COLLECTOR_DISABLE_LOCAL_UDP: "false"
      WEATHERFLOW_COLLECTOR_DISABLE_REMOTE_FORECAST: "false"
      WEATHERFLOW_COLLECTOR_DISABLE_REMOTE_REST: "false"
      WEATHERFLOW_COLLECTOR_DISABLE_REMOTE_SOCKET: "false"
      WEATHERFLOW_COLLECTOR_HEALTHCHECK: "true"
      WEATHERFLOW_COLLECTOR_HOST_HOSTNAME: HOME-0
      WEATHERFLOW_COLLECTOR_INFLUXDB_PASSWORD: x8egQTrf4bGl8Cs3XGyF1yE0b06pfgJe
      WEATHERFLOW_COLLECTOR_INFLUXDB_URL: http://wxfdashboardsaio_influxdb:8086/write?db=weatherflow
      WEATHERFLOW_COLLECTOR_INFLUXDB_USERNAME: weatherflow
      WEATHERFLOW_COLLECTOR_TOKEN: d041e722-8e57-41ba-9198-bcaf86e858b5
    restart: always
    depends_on:
      - "wxfdashboardsaio_influxdb"
    image: lux4rd0/weatherflow-collector:latest
    ports:
    - protocol: udp
      published: 50222
      target: 50222
    restart: always
volumes:
  wxfdashboardsaio-grafana-data:   
  wxfdashboardsaio-influxdb-data: 
version: '3.3'
