{
 "title": "Overview",
 "tags": [
  "weatherflow-collector",
  "influxdb"
 ],
 "time": { "from": "now/d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "station_name",
    "label": "Station Name",
    "query": "SHOW TAG VALUES WITH KEY = \"station_name\""
   },
   {
    "name": "tz",
    "label": "Time Zone",
    "query": "SHOW TAG VALUES WITH KEY = \"timezone\""
   }
  ]
 },
 "panels": [
  { "type": "dashlist", "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 0 },
   "options": {
    "content": "<center><img src=\"https://labs.lux4rd0.com/wp-content/uploads/2021/05/weatherflow_collector_header.png\"></center>"
   }
  },
  {
   "title": "Wind Speed",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "longitude" ], "type": "tag" },
      { "params": [ "latitude" ], "type": "tag" },
      { "params": [ "station_name" ], "type": "tag" }
     ],
     "measurement": "weatherflow_rapid_wind",
     "select": [
      [
       { "params": [ "wind_speed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " * 2.236936" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  { "title": "$station_name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "station_name" },
  {
   "title": "Current",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Current",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "weatherflow_obs",
     "select": [
      [
       { "params": [ "air_temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "collector_type", "operator": "=", "value": "remote-rest" },
      { "condition": "AND", "key": "station_name", "operator": "=~", "value": "/^$station_name$/" }
     ],
     "tz": "$tz"
    }
   ]
  },
  {
   "title": "Forecast High",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Forecast High",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "weatherflow_forecast_current",
     "query": "SELECT last(\"air_temp_high\") FROM \"weatherflow_forecast_daily\" WHERE (\"station_name\" =~ /^$station_name$/) AND $timeFilter GROUP BY time(1d) tz('$tz')",
     "select": [
      [
       { "params": [ "air_temp_high" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "station_name", "operator": "=~", "value": "/^$station_name$/" },
      { "condition": "AND", "key": "collector_type", "operator": "=", "value": "remote-forecast" }
     ],
     "tz": "$tz"
    }
   ]
  },
  {
   "title": "Observed High",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "alias": "Observed High",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "weatherflow_obs",
     "select": [
      [
       { "params": [ "air_temperature" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "collector_type", "operator": "=", "value": "remote-rest" },
      { "condition": "AND", "key": "station_name", "operator": "=~", "value": "/^$station_name$/" }
     ],
     "tz": "$tz"
    }
   ]
  },
  {
   "title": "Forecast Low",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Forecast High",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "weatherflow_forecast_current",
     "query": "SELECT last(\"air_temp_high\") FROM \"weatherflow_forecast_daily\" WHERE (\"station_name\" =~ /^$station_name$/) AND $timeFilter GROUP BY time(1d) tz('$tz')",
     "select": [
      [
       { "params": [ "air_temp_low" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "station_name", "operator": "=~", "value": "/^$station_name$/" },
      { "condition": "AND", "key": "collector_type", "operator": "=", "value": "remote-forecast" }
     ],
     "tz": "$tz"
    }
   ]
  },
  {
   "title": "Observed Low",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "alias": "Observed Low",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "weatherflow_obs",
     "select": [
      [
       { "params": [ "air_temperature" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "collector_type", "operator": "=", "value": "remote-rest" },
      { "condition": "AND", "key": "station_name", "operator": "=~", "value": "/^$station_name$/" }
     ],
     "tz": "$tz"
    }
   ]
  },
  {
   "title": "Station Pressure",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "pressurehg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Station Pressure",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "weatherflow_obs",
     "select": [
      [
       { "params": [ "station_pressure" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* .0295301" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "station_name", "operator": "=~", "value": "/^$station_name$/" },
      { "condition": "AND", "key": "collector_type", "operator": "=", "value": "remote-rest" }
     ],
     "tz": "$tz"
    }
   ]
  },
  {
   "title": "Wind",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Wind",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "weatherflow_rapid_wind",
     "select": [
      [
       { "params": [ "wind_speed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " * 2.236936" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "collector_type", "operator": "=", "value": "remote-socket" },
      { "condition": "AND", "key": "station_name", "operator": "=~", "value": "/^$station_name$/" }
     ],
     "tz": "$tz"
    }
   ]
  },
  {
   "title": "Wind Direction",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Wind Direction",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "weatherflow_rapid_wind",
     "select": [
      [
       { "params": [ "wind_direction" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "collector_type", "operator": "=", "value": "remote-socket" },
      { "condition": "AND", "key": "station_name", "operator": "=~", "value": "/^$station_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Chance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Chance",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "weatherflow_forecast_current",
     "select": [
      [
       { "params": [ "precip_probability" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "station_name", "operator": "=~", "value": "/^$station_name$/" },
      { "condition": "AND", "key": "collector_type", "operator": "=", "value": "remote-forecast" }
     ],
     "tz": "$tz"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Humidity",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "weatherflow_obs",
     "select": [
      [
       { "params": [ "relative_humidity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "station_name", "operator": "=~", "value": "/^$station_name$/" },
      { "condition": "AND", "key": "collector_type", "operator": "=", "value": "remote-rest" }
     ],
     "tz": "$tz"
    }
   ]
  }
 ]
}